dist: trusty

stages:
- test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: test
    name: Byzcoin
    language: go
    go: 1.15.x
    script: make update && cd cmd/byzcoin && ./test.sh

notifications:
  email: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache/go-build"
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache"
