version: "3.8"

services:
  node-1:
    image: ghcr.io/c4dt/byzcoin:latest
    build:
        context: ./
        dockerfile: Dockerfile
        target: byzcoin
        args:
          DOCKER_BUILDKIT: 1
    platform: linux/amd64
    ports:
      - "7770-7777:7770-7777"
      - "8080:3000"
    environment:
      - NODE=1
    volumes:
      - ./nodes/node-1:/byzcoin

  node-2:
    image: ghcr.io/c4dt/byzcoin:latest
    platform: linux/amd64
    environment:
      - NODE=2
    volumes:
      - ./nodes/node-2:/byzcoin
    network_mode: "service:node-1"

  node-3:
    image: ghcr.io/c4dt/byzcoin:latest
    platform: linux/amd64
    environment:
      - NODE=3
    volumes:
      - ./nodes/node-3:/byzcoin
    network_mode: "service:node-1"

  node-4:
    image: ghcr.io/c4dt/byzcoin:latest
    platform: linux/amd64
    environment:
      - NODE=4
    volumes:
      - ./nodes/node-4:/byzcoin
    network_mode: "service:node-1"

  login:
    image: ghcr.io/c4dt/byzcoin-web:latest
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
      target: web
      args:
        DOCKER_BUILDKIT: 1
    network_mode: "service:node-1"
