FROM node:12 as builder-omniledger
RUN git clone https://github.com/c4dt/omniledger -b archive /omniledger
WORKDIR /omniledger/webapp
RUN npm ci && npm link ../dynacred
RUN npx ng build --prod --base-href /login/ --deploy-url /login/ --aot --output-path www
COPY --from=byzcoin-builder /byzcoin/nodes/config.toml www/assets/

FROM node:14 as builder-olexplorer
RUN git clone https://github.com/c4dt/ol-explorer -b archive /ol-explorer
WORKDIR /ol-explorer
RUN npm ci
RUN npx ng build --prod --base-href /ol-explorer/ --deploy-url /ol-explorer/ --output-path www
COPY --from=byzcoin-builder /byzcoin/nodes/config.toml www/assets/config.toml

FROM node:14 as builder-columbus
RUN git clone https://github.com/c4dt/columbus-united -b archive /columbus
WORKDIR /columbus
RUN npm i
RUN npm run bundle
COPY --from=byzcoin-builder /byzcoin/nodes/config.toml assets/config.toml

FROM lipanski/docker-static-website:latest as web
#FROM python:latest
COPY httpd.conf .
COPY --from=builder-omniledger /omniledger/webapp/www/ login/
COPY --from=builder-olexplorer /ol-explorer/www/ ol-explorer/
COPY --from=builder-columbus /columbus/index.html columbus/
COPY --from=builder-columbus /columbus/dist/ columbus/dist/
COPY --from=builder-columbus /columbus/assets/ columbus/assets/
