version: "3.0"

services:
  byzcoin:
    environment:
      # ADDRESS_NODE should always be tls:// - tcp:// is insecure and should
      # not be used.
      - ADDRESS_NODE=tls://byzcoin.c4dt.org:7770
      # ADDRESS_WS can be either http:// or https:// - for most of the use-cases
      # you want this to be https://, so that secure webpages can access the node.
      - ADDRESS_WS=http://byzcoin.c4dt.org:7771
      # A short description of your node that will be visible to the outside.
      - DESCRIPTION=New ByzCoin node
      # Whether to use TLS in the conodes. It is tested against 'false'. So
      # anything different from 'false' will be interpreted as true.
      - USE_TLS=false
      # WS_SSL_* is ignored if ADDRESS_WS is http or USE_TLS=false. These files 
      # need to be in the ~/byzcoin directory before the node is started.
      - WS_SSL_CHAIN=fullchain.pem
      - WS_SSL_KEY=privkey.pem
      # ID of the byzcoin to follow - this corresponds to the DEDIS byzcoin.
      - BYZCOIN_ID=9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
      # How much debugging output - 0 is none, 1 is important ones, 2 is
      # interesting, 3 is detailed, 4 is lots of details, and 5 is too detailed for
      # most purposes.
      - DEBUG_LVL=2
      # Whether to niceify the debug outputs. If you put this to `true`, you should
      # have a black background in the terminal.
      - DEBUG_COLOR=false
      # If set to true, adds a timestamp to each log-message
      - DEBUG_TIME=true
      # Send the logging information to a graylog instance. Optional, can be put to
      # "" if not needed.
      - GRAYLOG=
      # Send tracing information to honeycomb.io. The format is: api_key:dataset.
      # If no key is set, tracing is disabled.
      - HONEYCOMB_API_KEY=
    ports:
      - "7770-7771:7770-7771"
    image: c4dt/byzcoin:latest
    volumes:
      # Where the byzcoin data resides on the host. Do not change the :/byzcoin
      # part, only the ~/byzcoin.
      - ~/byzcoin:/byzcoin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --label-enable
