name: docker-tag

on:
  schedule:
    - cron: '42 0 * * 0,2,3,4,5,6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set docker credentials
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push new docker image
        run: make docker-push-new
