name: update-code

on:
  schedule:
    - cron: '42 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Fetch latest code
        run: make update

      - name: Replay
        run: |
          ( cd upstream/cothority; go build -o ../../bcadmin ./byzcoin/bcadmin )
          wget --progress=dot:giga https://demo.c4dt.org/omniledger/cached.db
          if [ "${GITHUB_REF##*/}" != master ]; then export BLOCKS="--blocks 256"; fi
          ./bcadmin --debug 1 db replay cached.db --summarize 100 $BLOCKS 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3

      - name: Set git credentials
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Update github repo
        run: |
          if [ "${GITHUB_REF##*/}" = "master" ]; then
            git add .
            git commit -am "Automatic update on $( date )"
            git push
          fi

      - name: Set docker credentials
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push new docker image
        run: make docker-push-new
